# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 891a724fa60cece96c5422bd0221b448eb0a79e9f72935464c0d99c577e99a3db953425a6f3c2ddf9e840b0b49c3abf7fd51d1105f12b1458ea762857be911a8

test:
  secret_key_base: d78101a99b1bc428ad3ffb7851dc249621f6510eda377e948787e3a0f4a0f3dc44e03c78a6333b26099fe438af20f831bdc05590c2dd5c4f5d8bc06bff6a09ed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
